// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface ClergyMember {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  title?: string;
  photo?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  bio?: string;
  email?: string;
  phone?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Event {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  description?: string;
  start_date?: string;
  end_date?: string;
  location?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Faq {
  id: string;
  slug: string | null;
  status: string;
  question: string;
  answer?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Ministry {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  icon?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  summary?: string;
  content?: PortableTextBlock[];
  schedule?: string;
  contact_name?: string;
  contact_email?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  excerpt?: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    clergy: ClergyMember;
    events: Event;
    faqs: Faq;
    ministries: Ministry;
    pages: Page;
    posts: Post;
  }
}